import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1707668841248 implements MigrationInterface {
    name = 'Migration1707668841248'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`members\` DROP FOREIGN KEY \`FK_da404b5fd9c390e25338996e2d1\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP FOREIGN KEY \`FK_eee0b30f2ccac9355b8c28f7391\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP FOREIGN KEY \`FK_fcc994c1b73acbb700f9b7c5a21\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP FOREIGN KEY \`FK_5cf2746dd28948f522783ebf760\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP FOREIGN KEY \`FK_d752442f45f258a8bdefeebb2f2\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP FOREIGN KEY \`FK_8e1ad3d25c838fc428891d2800d\``);
        await queryRunner.query(`ALTER TABLE \`location\` DROP FOREIGN KEY \`FK_3f5f755d1eebc84dd2c5f5d7aa3\``);
        await queryRunner.query(`ALTER TABLE \`location\` DROP FOREIGN KEY \`FK_7ce24632983d8147b8cab7a2642\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_05535bc695e9f7ee104616459d3\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_7540635fef1922f0b156b9ef74f\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP FOREIGN KEY \`FK_22f39cf868447b6b41a04037679\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP FOREIGN KEY \`FK_41397c85ba7b68f31beee207854\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP FOREIGN KEY \`FK_55fa339a3c13ddd6755ac3f961b\``);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` DROP FOREIGN KEY \`FK_39e437ea50812de502d8391e05b\``);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` DROP FOREIGN KEY \`FK_548c10d86ac37592d35a7ea6e93\``);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` DROP FOREIGN KEY \`FK_2834a0037a62c66fc7b31ab523c\``);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` DROP FOREIGN KEY \`FK_c7fab0901a26a42a0a6cbbecc46\``);
        await queryRunner.query(`DROP INDEX \`idx_user_id\` ON \`profile\``);
        await queryRunner.query(`DROP INDEX \`REL_5cf2746dd28948f522783ebf76\` ON \`profile\``);
        await queryRunner.query(`DROP INDEX \`REL_d752442f45f258a8bdefeebb2f\` ON \`profile\``);
        await queryRunner.query(`DROP INDEX \`REL_8e1ad3d25c838fc428891d2800\` ON \`tournament\``);
        await queryRunner.query(`DROP INDEX \`REL_3f5f755d1eebc84dd2c5f5d7aa\` ON \`location\``);
        await queryRunner.query(`DROP INDEX \`REL_7ce24632983d8147b8cab7a264\` ON \`location\``);
        await queryRunner.query(`DROP INDEX \`REL_41397c85ba7b68f31beee20785\` ON \`team\``);
        await queryRunner.query(`DROP INDEX \`REL_55fa339a3c13ddd6755ac3f961\` ON \`team\``);
        await queryRunner.query(`DROP INDEX \`IDX_39e437ea50812de502d8391e05\` ON \`tournament_teams_team\``);
        await queryRunner.query(`DROP INDEX \`IDX_548c10d86ac37592d35a7ea6e9\` ON \`tournament_teams_team\``);
        await queryRunner.query(`DROP INDEX \`IDX_2834a0037a62c66fc7b31ab523\` ON \`users_chats_chats\``);
        await queryRunner.query(`DROP INDEX \`IDX_c7fab0901a26a42a0a6cbbecc4\` ON \`users_chats_chats\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP COLUMN \`join_date\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP COLUMN \`profile_id\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP COLUMN \`team_id\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`skill_level\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`preferred_position\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`image_url\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`location_id\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`team_limit\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`register_deadline\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`tournament_date\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`winning_team_id\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`runner_up_team_id\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`is_finished\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`is_cancelled\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`location_id\``);
        await queryRunner.query(`ALTER TABLE \`location\` DROP COLUMN \`profile_id\``);
        await queryRunner.query(`ALTER TABLE \`location\` DROP COLUMN \`tournament_id\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`chat_id\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`author_id\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP COLUMN \`total_members\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP COLUMN \`location_id\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP COLUMN \`creator_id\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP COLUMN \`chat_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`is_admin\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`is_social_login_user\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`kakao_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`google_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`apple_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` ADD PRIMARY KEY (\`team_id\`)`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` DROP COLUMN \`tournament_id\``);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` DROP COLUMN \`team_id\``);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` ADD PRIMARY KEY (\`chats_id\`)`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` DROP COLUMN \`users_id\``);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` DROP COLUMN \`chats_id\``);
        await queryRunner.query(`ALTER TABLE \`members\` ADD \`joinDate\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD \`profileId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD \`teamId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`skillLevel\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`preferredPosition\` enum ('Goalkeeper', 'Center Back', 'Right Back', 'Left Back', 'Defensive Midfielder', 'Central Midfielder', 'Attacking Midfielder', 'Striker', 'Forward', 'Right Winger', 'Left Winger') NOT NULL DEFAULT 'Attacking Midfielder'`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`imageUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`deletedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`locationId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD UNIQUE INDEX \`IDX_432056041df0e4337b17ff7b09\` (\`locationId\`)`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD UNIQUE INDEX \`IDX_a24972ebd73b106250713dcddd\` (\`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`teamLimit\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`registerDeadline\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`tournamentDate\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`winningTeamId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`runnerUpTeamId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`isFinished\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`isCancelled\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`locationId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD UNIQUE INDEX \`IDX_c004010710b8b1daecc30b49c0\` (\`locationId\`)`);
        await queryRunner.query(`ALTER TABLE \`location\` ADD \`profileId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`location\` ADD UNIQUE INDEX \`IDX_3d6d6403e11c790ed13afce8fc\` (\`profileId\`)`);
        await queryRunner.query(`ALTER TABLE \`location\` ADD \`tournamentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`location\` ADD UNIQUE INDEX \`IDX_eee898f84d13312a749232e831\` (\`tournamentId\`)`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`chatId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`authorId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD \`totalMembers\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD \`locationId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD \`creatorId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD UNIQUE INDEX \`IDX_221f660916dd8a58ff7269aaf8\` (\`creatorId\`)`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD \`chatId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD UNIQUE INDEX \`IDX_e29bb03ca8b6aba030dda14039\` (\`chatId\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`isAdmin\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`isSocialLoginUser\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`kakaoId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`googleId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`appleId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` ADD \`tournamentId\` int NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` ADD \`teamId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` ADD PRIMARY KEY (\`tournamentId\`, \`teamId\`)`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` ADD \`usersId\` int NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` ADD \`chatsId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` ADD PRIMARY KEY (\`usersId\`, \`chatsId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`idx_user_id\` ON \`profile\` (\`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_432056041df0e4337b17ff7b09\` ON \`profile\` (\`locationId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_a24972ebd73b106250713dcddd\` ON \`profile\` (\`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_c004010710b8b1daecc30b49c0\` ON \`tournament\` (\`locationId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_3d6d6403e11c790ed13afce8fc\` ON \`location\` (\`profileId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_eee898f84d13312a749232e831\` ON \`location\` (\`tournamentId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_221f660916dd8a58ff7269aaf8\` ON \`team\` (\`creatorId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_e29bb03ca8b6aba030dda14039\` ON \`team\` (\`chatId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_48e20749264d1c0f2cb794decf\` ON \`tournament_teams_team\` (\`tournamentId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_36eef76549cea08a85c1644dd6\` ON \`tournament_teams_team\` (\`teamId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_017810da2080af92ae589a06db\` ON \`users_chats_chats\` (\`usersId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_6628b681b44362637c96ad2fab\` ON \`users_chats_chats\` (\`chatsId\`)`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD CONSTRAINT \`FK_839756572a2c38eb5a3b563126e\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD CONSTRAINT \`FK_ee05ebf5899e88e1e0aac0737af\` FOREIGN KEY (\`profileId\`) REFERENCES \`profile\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD CONSTRAINT \`FK_b0fe0d62c4fd4633321fdf9616f\` FOREIGN KEY (\`teamId\`) REFERENCES \`team\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD CONSTRAINT \`FK_432056041df0e4337b17ff7b09d\` FOREIGN KEY (\`locationId\`) REFERENCES \`location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD CONSTRAINT \`FK_a24972ebd73b106250713dcddd9\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD CONSTRAINT \`FK_c004010710b8b1daecc30b49c0f\` FOREIGN KEY (\`locationId\`) REFERENCES \`location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`location\` ADD CONSTRAINT \`FK_3d6d6403e11c790ed13afce8fcd\` FOREIGN KEY (\`profileId\`) REFERENCES \`profile\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`location\` ADD CONSTRAINT \`FK_eee898f84d13312a749232e831b\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_36bc604c820bb9adc4c75cd4115\` FOREIGN KEY (\`chatId\`) REFERENCES \`chats\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_819e6bb0ee78baf73c398dc707f\` FOREIGN KEY (\`authorId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD CONSTRAINT \`FK_7a6d4f00c458cdf973385e1ff43\` FOREIGN KEY (\`locationId\`) REFERENCES \`location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD CONSTRAINT \`FK_221f660916dd8a58ff7269aaf8c\` FOREIGN KEY (\`creatorId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD CONSTRAINT \`FK_e29bb03ca8b6aba030dda14039c\` FOREIGN KEY (\`chatId\`) REFERENCES \`chats\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` ADD CONSTRAINT \`FK_48e20749264d1c0f2cb794decf3\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` ADD CONSTRAINT \`FK_36eef76549cea08a85c1644dd6e\` FOREIGN KEY (\`teamId\`) REFERENCES \`team\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` ADD CONSTRAINT \`FK_017810da2080af92ae589a06db8\` FOREIGN KEY (\`usersId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` ADD CONSTRAINT \`FK_6628b681b44362637c96ad2fab0\` FOREIGN KEY (\`chatsId\`) REFERENCES \`chats\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` DROP FOREIGN KEY \`FK_6628b681b44362637c96ad2fab0\``);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` DROP FOREIGN KEY \`FK_017810da2080af92ae589a06db8\``);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` DROP FOREIGN KEY \`FK_36eef76549cea08a85c1644dd6e\``);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` DROP FOREIGN KEY \`FK_48e20749264d1c0f2cb794decf3\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP FOREIGN KEY \`FK_e29bb03ca8b6aba030dda14039c\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP FOREIGN KEY \`FK_221f660916dd8a58ff7269aaf8c\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP FOREIGN KEY \`FK_7a6d4f00c458cdf973385e1ff43\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_819e6bb0ee78baf73c398dc707f\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_36bc604c820bb9adc4c75cd4115\``);
        await queryRunner.query(`ALTER TABLE \`location\` DROP FOREIGN KEY \`FK_eee898f84d13312a749232e831b\``);
        await queryRunner.query(`ALTER TABLE \`location\` DROP FOREIGN KEY \`FK_3d6d6403e11c790ed13afce8fcd\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP FOREIGN KEY \`FK_c004010710b8b1daecc30b49c0f\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP FOREIGN KEY \`FK_a24972ebd73b106250713dcddd9\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP FOREIGN KEY \`FK_432056041df0e4337b17ff7b09d\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP FOREIGN KEY \`FK_b0fe0d62c4fd4633321fdf9616f\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP FOREIGN KEY \`FK_ee05ebf5899e88e1e0aac0737af\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP FOREIGN KEY \`FK_839756572a2c38eb5a3b563126e\``);
        await queryRunner.query(`DROP INDEX \`IDX_6628b681b44362637c96ad2fab\` ON \`users_chats_chats\``);
        await queryRunner.query(`DROP INDEX \`IDX_017810da2080af92ae589a06db\` ON \`users_chats_chats\``);
        await queryRunner.query(`DROP INDEX \`IDX_36eef76549cea08a85c1644dd6\` ON \`tournament_teams_team\``);
        await queryRunner.query(`DROP INDEX \`IDX_48e20749264d1c0f2cb794decf\` ON \`tournament_teams_team\``);
        await queryRunner.query(`DROP INDEX \`REL_e29bb03ca8b6aba030dda14039\` ON \`team\``);
        await queryRunner.query(`DROP INDEX \`REL_221f660916dd8a58ff7269aaf8\` ON \`team\``);
        await queryRunner.query(`DROP INDEX \`REL_eee898f84d13312a749232e831\` ON \`location\``);
        await queryRunner.query(`DROP INDEX \`REL_3d6d6403e11c790ed13afce8fc\` ON \`location\``);
        await queryRunner.query(`DROP INDEX \`REL_c004010710b8b1daecc30b49c0\` ON \`tournament\``);
        await queryRunner.query(`DROP INDEX \`REL_a24972ebd73b106250713dcddd\` ON \`profile\``);
        await queryRunner.query(`DROP INDEX \`REL_432056041df0e4337b17ff7b09\` ON \`profile\``);
        await queryRunner.query(`DROP INDEX \`idx_user_id\` ON \`profile\``);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` ADD PRIMARY KEY (\`usersId\`)`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` DROP COLUMN \`chatsId\``);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` DROP COLUMN \`usersId\``);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` ADD PRIMARY KEY (\`tournamentId\`)`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` DROP COLUMN \`teamId\``);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` DROP COLUMN \`tournamentId\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`appleId\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`googleId\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`kakaoId\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`isSocialLoginUser\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`isAdmin\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP INDEX \`IDX_e29bb03ca8b6aba030dda14039\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP COLUMN \`chatId\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP INDEX \`IDX_221f660916dd8a58ff7269aaf8\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP COLUMN \`creatorId\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP COLUMN \`locationId\``);
        await queryRunner.query(`ALTER TABLE \`team\` DROP COLUMN \`totalMembers\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`authorId\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP COLUMN \`chatId\``);
        await queryRunner.query(`ALTER TABLE \`location\` DROP INDEX \`IDX_eee898f84d13312a749232e831\``);
        await queryRunner.query(`ALTER TABLE \`location\` DROP COLUMN \`tournamentId\``);
        await queryRunner.query(`ALTER TABLE \`location\` DROP INDEX \`IDX_3d6d6403e11c790ed13afce8fc\``);
        await queryRunner.query(`ALTER TABLE \`location\` DROP COLUMN \`profileId\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP INDEX \`IDX_c004010710b8b1daecc30b49c0\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`locationId\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`isCancelled\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`isFinished\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`runnerUpTeamId\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`winningTeamId\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`tournamentDate\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`registerDeadline\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP COLUMN \`teamLimit\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP INDEX \`IDX_a24972ebd73b106250713dcddd\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP INDEX \`IDX_432056041df0e4337b17ff7b09\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`locationId\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`imageUrl\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`preferredPosition\``);
        await queryRunner.query(`ALTER TABLE \`profile\` DROP COLUMN \`skillLevel\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP COLUMN \`teamId\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP COLUMN \`profileId\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`members\` DROP COLUMN \`joinDate\``);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` ADD \`chats_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` ADD PRIMARY KEY (\`chats_id\`)`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` ADD \`users_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` ADD PRIMARY KEY (\`users_id\`, \`chats_id\`)`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` ADD \`team_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` ADD PRIMARY KEY (\`team_id\`)`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` ADD \`tournament_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` ADD PRIMARY KEY (\`tournament_id\`, \`team_id\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`apple_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`google_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`kakao_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`is_social_login_user\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`is_admin\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD \`chat_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD \`creator_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD \`location_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD \`total_members\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`author_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD \`chat_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`location\` ADD \`tournament_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`location\` ADD \`profile_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`location_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`is_cancelled\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`is_finished\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`runner_up_team_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`winning_team_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`tournament_date\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`register_deadline\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD \`team_limit\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`location_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`deleted_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`image_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`preferred_position\` enum ('Goalkeeper', 'Center Back', 'Right Back', 'Left Back', 'Defensive Midfielder', 'Central Midfielder', 'Attacking Midfielder', 'Striker', 'Forward', 'Right Winger', 'Left Winger') NOT NULL DEFAULT 'Attacking Midfielder'`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD \`skill_level\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD \`team_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD \`profile_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD \`join_date\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE INDEX \`IDX_c7fab0901a26a42a0a6cbbecc4\` ON \`users_chats_chats\` (\`chats_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_2834a0037a62c66fc7b31ab523\` ON \`users_chats_chats\` (\`users_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_548c10d86ac37592d35a7ea6e9\` ON \`tournament_teams_team\` (\`tournament_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_39e437ea50812de502d8391e05\` ON \`tournament_teams_team\` (\`team_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_55fa339a3c13ddd6755ac3f961\` ON \`team\` (\`chat_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_41397c85ba7b68f31beee20785\` ON \`team\` (\`creator_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_7ce24632983d8147b8cab7a264\` ON \`location\` (\`profile_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_3f5f755d1eebc84dd2c5f5d7aa\` ON \`location\` (\`tournament_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_8e1ad3d25c838fc428891d2800\` ON \`tournament\` (\`location_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_d752442f45f258a8bdefeebb2f\` ON \`profile\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_5cf2746dd28948f522783ebf76\` ON \`profile\` (\`location_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`idx_user_id\` ON \`profile\` (\`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` ADD CONSTRAINT \`FK_c7fab0901a26a42a0a6cbbecc46\` FOREIGN KEY (\`chats_id\`) REFERENCES \`chats\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users_chats_chats\` ADD CONSTRAINT \`FK_2834a0037a62c66fc7b31ab523c\` FOREIGN KEY (\`users_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` ADD CONSTRAINT \`FK_548c10d86ac37592d35a7ea6e93\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`tournament\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`tournament_teams_team\` ADD CONSTRAINT \`FK_39e437ea50812de502d8391e05b\` FOREIGN KEY (\`team_id\`) REFERENCES \`team\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD CONSTRAINT \`FK_55fa339a3c13ddd6755ac3f961b\` FOREIGN KEY (\`chat_id\`) REFERENCES \`chats\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD CONSTRAINT \`FK_41397c85ba7b68f31beee207854\` FOREIGN KEY (\`creator_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team\` ADD CONSTRAINT \`FK_22f39cf868447b6b41a04037679\` FOREIGN KEY (\`location_id\`) REFERENCES \`location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_7540635fef1922f0b156b9ef74f\` FOREIGN KEY (\`chat_id\`) REFERENCES \`chats\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_05535bc695e9f7ee104616459d3\` FOREIGN KEY (\`author_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`location\` ADD CONSTRAINT \`FK_7ce24632983d8147b8cab7a2642\` FOREIGN KEY (\`profile_id\`) REFERENCES \`profile\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`location\` ADD CONSTRAINT \`FK_3f5f755d1eebc84dd2c5f5d7aa3\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`tournament\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD CONSTRAINT \`FK_8e1ad3d25c838fc428891d2800d\` FOREIGN KEY (\`location_id\`) REFERENCES \`location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD CONSTRAINT \`FK_d752442f45f258a8bdefeebb2f2\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`profile\` ADD CONSTRAINT \`FK_5cf2746dd28948f522783ebf760\` FOREIGN KEY (\`location_id\`) REFERENCES \`location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD CONSTRAINT \`FK_fcc994c1b73acbb700f9b7c5a21\` FOREIGN KEY (\`profile_id\`) REFERENCES \`profile\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD CONSTRAINT \`FK_eee0b30f2ccac9355b8c28f7391\` FOREIGN KEY (\`team_id\`) REFERENCES \`team\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`members\` ADD CONSTRAINT \`FK_da404b5fd9c390e25338996e2d1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
